#!/bin/bash

UTIL_DIR=Spacy/Util
DETAIL_DIR=Detail
BUFFER_SIZE=16
INCLUDE_DIR=$1

COMMAND=/home/lars/Libraries/build-llvm2/bin/clang-type-erase
COMMON_ARGS="-detail-dir=$DETAIL_DIR -include-dir=$INCLUDE_DIR -util-dir=$UTIL_DIR -util-include-dir=<$UTIL_DIR/type_erasure_util.h>"
SMALL_SBO_ARGS="-sbo -buffer-size=$BUFFER_SIZE"

function generate_interface {
echo "generate $1"
$COMMAND $COMMON_ARGS $3 -target-dir=$2 $1 -std=c++14 -I.. -x c++-header
}

function generate_interfaces {
generate_interface zeroVectorCreator.hh Spacy ""
generate_interface          operator.hh Spacy "$SMALL_SBO_ARGS"
generate_interface    linearOperator.hh Spacy "$SMALL_SBO_ARGS"
generate_interface        c1Operator.hh Spacy "$SMALL_SBO_ARGS"
generate_interface   dynamicOperator.hh Spacy "$SMALL_SBO_ARGS"
generate_interface        functional.hh Spacy "$SMALL_SBO_ARGS"
generate_interface      c1Functional.hh Spacy "$SMALL_SBO_ARGS"
generate_interface      c2Functional.hh Spacy "$SMALL_SBO_ARGS"
generate_interface            vector.hh Spacy "$SMALL_SBO_ARGS"
generate_interface linearSolver.hh Spacy ""
}

function generate_cg_interfaces {
# generate interface for conjugate gradient methods
echo "for CG: generate terminationCriterion.hh"
CG_DIR=Spacy/Algorithm/CG
mkdir -p $INCLUDE_DIR/$CG_DIR/$DETAIL_DIR
generate_interface TerminationCriterion.h $CG_DIR ""
generate_interface Regularization.h $CG_DIR ""
}

function generate_logger_interfaces {
# generate interface for printer of logger
echo "for logger: generate printer.hh"
mkdir -p $INCLUDE_DIR/$UTIL_DIR/$DETAIL_DIR
generate_interface Printer.h $UTIL_DIR ""
}

mkdir -p $INCLUDE_DIR/Spacy/$DETAIL_DIR
generate_interfaces
generate_cg_interfaces
generate_logger_interfaces
