#pragma once

#include "KaskadeParabolic/scalarProduct.hh"
#include "KaskadeParabolic/vectorSpace.hh"
#include "KaskadeParabolic/c1Operator.hh"
#include "KaskadeParabolic/c2Functional.hh"
#include "KaskadeParabolic/directBlockPreconditioner.hh"
#include "KaskadeParabolic/directSolver.hh"
#include "KaskadeParabolic/gridManager.hh"
#include "KaskadeParabolic/l2Product.hh"
#include "KaskadeParabolic/linearBlockOperator.hh"
#include "KaskadeParabolic/linearBlockOperatorSpace.hh"
#include "KaskadeParabolic/util.hh"
#include "KaskadeParabolic/vector.hh"
#include "KaskadeParabolic/writeVTK.hh"
#include "KaskadeParabolic/SubspaceRelation.h"
#include "KaskadeParabolic/LinearOperator.h"
#include "KaskadeParabolic/MassMatrix.h"
#include "KaskadeParabolic/PDESolver.h"
#include "KaskadeParabolic/PDESolverSurr.h"
#include "KaskadeParabolic/preconditioner.hh"
#include "KaskadeParabolic/DirectSolver.h"

// #include "KaskadeParabolic/ModelPredictiveController.hh"
// #include "KaskadeParabolic/errorEstimator.hh"
